### ISSUE TITLE
Control panel

### ISSUE THREAD

**Issue by coppolaemilio** [franciscop/UserManager#3]
It would be nice to have a control panel where to check how many users there are on the system and some other stats about them. Also the possibility to set admin privileges or block users.

**Comment by franciscop** [comment]
This is in development. However, it won't be ready for next version yet.

**Comment by franciscop** [comment]
Project closed

**Comment by coppolaemilio** [comment]
Fue bonito mientras duró :cry:

**Comment by franciscop** [comment]
Sii, pero viendo tantos issues, los que no son necesarios los cierro. El proyecto está muerto oficialmente, pero
- a alguien le pueden servir algunas partes
- es algo que he hecho y no quería borrarlo
  Por eso he decidido cerrar los issues no críticos
